//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

// SeaORM 实体模块预定义
pub mod prelude;

// 动态监控数据实体模块
pub mod dynamic_monitoring;
// 静态监控数据实体模块
pub mod static_monitoring;
// 任务实体模块
pub mod task;
// 令牌实体模块
pub mod token;
