//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub use super::crontab::Entity as Crontab;
pub use super::crontab_result::Entity as CrontabResult;
pub use super::dynamic_monitoring::Entity as DynamicMonitoring;
pub use super::kv::Entity as Kv;
pub use super::static_monitoring::Entity as StaticMonitoring;
pub use super::task::Entity as Task;
pub use super::token::Entity as Token;
