use crate::error::Result;
use tracing::{error, warn};
use uuid::Uuid;

/// 获取设备稳定 UUID，Windows / macOS / Linux 下的唯一 UUID 生成器，在同一系统下不变
///
/// # Errors
///
/// 当无法获取机器 ID 时返回错误
pub fn get_stable_device_uuid() -> Result<Uuid> {
    use uuid::Uuid;
    let mut machine_id = machine_uid::get().unwrap_or_else(|e| {
        error!("无法获取系统 ID: {e}, 使用 fallback");
        "fallback-device-id".to_string()
    });

    if cfg!(feature = "for-agent") {
        machine_id.push_str("-agent");
    } else {
        machine_id.push_str("-server");
    }

    Ok(Uuid::new_v5(&Uuid::NAMESPACE_OID, machine_id.as_bytes()))
}

/// 比较设置的 UUID 与设备生成的 UUID 是否匹配
///
/// # 参数
/// * `set_uuid` - 设置的 UUID
///
/// # Errors
///
/// 当获取稳定 UUID 失败时返回错误
pub fn compare_uuid(set_uuid: Uuid) -> Result<bool> {
    let stable_uuid = get_stable_device_uuid()?;
    if set_uuid == stable_uuid {
        Ok(true)
    } else {
        warn!(
            "The `uuid` [{set_uuid}] configured in profile does not match the uuid [{stable_uuid}] generated by the environment."
        );
        warn!("This may result in undefined behavior.");
        warn!("Modify the UUID with caution!");
        Ok(false)
    }
}
